export const NIGERIAN_STATES = [
  { value: "ABIA", label: "ABIA" },
  { value: "ADAMAWA", label: "ADAMAWA" },
  { value: "AKWA IBOM", label: "AKWA IBOM" },
  { value: "ANAMBRA", label: "ANAMBRA" },
  { value: "BAUCHI", label: "BAUCHI" },
  { value: "BAYELSA", label: "BAYELSA" },
  { value: "BENUE", label: "BENUE" },
  { value: "BORNO", label: "BORNO" },
  { value: "CROSS RIVER", label: "CROSS RIVER" },
  { value: "DELTA", label: "DELTA" },
  { value: "EBONYI", label: "EBONYI" },
  { value: "EDO", label: "EDO" },
  { value: "EKITI", label: "EKITI" },
  { value: "ENUGU", label: "ENUGU" },
  { value: "GOMBE", label: "GOMBE" },
  { value: "IMO", label: "IMO" },
  { value: "JIGAWA", label: "JIGAWA" },
  { value: "KADUNA", label: "KADUNA" },
  { value: "KANO", label: "KANO" },
  { value: "KATSINA", label: "KATSINA" },
  { value: "KEBBI", label: "KEBBI" },
  { value: "KOGI", label: "KOGI" },
  { value: "KWARA", label: "KWARA" },
  { value: "LAGOS", label: "LAGOS" },
  { value: "NASARAWA", label: "NASARAWA" },
  { value: "NIGER", label: "NIGER" },
  { value: "OGUN", label: "OGUN" },
  { value: "ONDO", label: "ONDO" },
  { value: "OSUN", label: "OSUN" },
  { value: "OYO", label: "OYO" },
  { value: "PLATEAU", label: "PLATEAU" },
  { value: "RIVERS", label: "RIVERS" },
  { value: "SOKOTO", label: "SOKOTO" },
  { value: "TARABA", label: "TARABA" },
  { value: "YOBE", label: "YOBE" },
  { value: "ZAMFARA", label: "ZAMFARA" },
  { value: "FCT", label: "FCT" },
];
